secret:
  jwt:
    access:
      key: ${ACCESS_TOKEN_KEY}
      expired-in: 3600000
    refresh:
      key: ${REFRESH_TOKEN_KEY}
      expired-in: 1209600000

logging.level:
  org.hibernate.SQL: debug # sql ??
